sudo: required
services:
  - docker

before_install:
  - docker build -t asadbinahmed/complex -f ./client/Dockerfile.dev ./client

script:
  - docker run asadbinahmed/complex npm run test -- --coverage

after_success:
  - docker build -t asadbinahmed/multi-client ./client
  - docker build -t asadbinahmed/multi-nginx ./nginx
  - docker build -t asadbinahmed/multi-server ./server
  - docker build -t asadbinahmed/multi-worker ./worker
  # login to docker cli
 
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  

  # take those images and push them to docker hub
  - docker push asadbinahmed/multi-client
  - docker push asadbinahmed/multi-nginx
  - docker push asadbinahmed/multi-server
  - docker push asadbinahmed/multi-worker